[package]
name = "nsq-in-rust"
version = "0.1.0"
authors = ["belltoy <belltoy@gmail.com>"]

[dependencies]
tokio = "0.1"
tokio-io = "0.1"
tokio-codec = "0.1"
futures = "0.1"
hyper = "0.12"
serde = "1"
serde_json = "1"
bytes = "0.4"
byteorder = "1"
hostname = "0.1"
